### ISSUE TITLE
Erro ao rodar "npm run dev"

### ISSUE THREAD

**Issue by willfreire** [michelpf/bck-eth-dapp-vaccine-control#1]
Olá, estou seguindo o passo a passo conforme documentado, mas no final de tudo ao rodar o comando `$ npm run dev`, ocorre o seguinte erro:

> Error: watch /var/www/bck-eth-dapp-vaccine-control ENOSPC
    at FSWatcher.start (fs.js:1402:19)
    at Object.fs.watch (fs.js:1428:11)
    at createFsWatchInstance (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:171:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/var/www/bck-eth-dapp-vaccine-control/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:171:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bck-vaccine-control@1.0.0 dev: `lite-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bck-vaccine-control@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Como resolver isto?

Abs.

**Comment by michelpf** [comment]
Você rodou `npm install` antes?

**Comment by willfreire** [comment]
> Você rodou npm install antes?

Sim. Finalizou sem erros.

**Comment by michelpf** [comment]
Para funcionar, você precisa seguir estes passos:

1. Instalar o truffle, `npm install truffle –g`

2. Faça o download do Ganache

3. Abra o Ganache, configure a porta para 8545 (pois está assim na configuração do truffle.js)

```
...
development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*", // Match any network id
    }
...
```

4. No console, envie os comandos `truffle compile`, `truffle test` e `truffle migrate --reset`
Neste passo, me mostre qual foi o resultado

5. Rode na pasta do projeto o `npm install` para a instalação do lite-server e demais pacotes

6. Execute o `npm run dev`.

**Comment by willfreire** [comment]
Agora sim, funcionou:

<pre><font color="#8AE234"><b>willfreire@willfreire</b></font>:<font color="#729FCF"><b>/var/www/bck-eth-dapp-vaccine-control</b></font>$ truffle compile
<font color="#8AE234"><b>willfreire@willfreire</b></font>:<font color="#729FCF"><b>/var/www/bck-eth-dapp-vaccine-control</b></font>$ truffle test
Using network &apos;development&apos;.

Compiling ./contracts/VaccineControl.sol...
Compiling ./test/TestVaccineControl.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...


  TestVaccineControl
  <font color="#4E9A06">  ✓</font><font color="#555753"> testAddingNewPerson</font><font color="#CC0000"> (134ms)</font>
  <font color="#4E9A06">  ✓</font><font color="#555753"> testAddingNewVaccine</font><font color="#CC0000"> (186ms)</font>


<font color="#8AE234"> </font><font color="#4E9A06"> 2 passing</font><font color="#555753"> (1s)</font>

<font color="#8AE234"><b>willfreire@willfreire</b></font>:<font color="#729FCF"><b>/var/www/bck-eth-dapp-vaccine-control</b></font>$ truffle migrate --reset
Using network &apos;development&apos;.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0xb20908a1a1cf4dc0b45a438b7cb66cf68428f18f037726bbb048fc16a8ad5e01
  Migrations: 0x13ababc69ab1cc4a25e691be64f6c0d51216de51
Saving successful migration to network...
  ... 0x77f947080e7a9f1c0ee5dc54e18ecc1670c0ce7454c23e19809a1acfdf79abed
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing VaccineControl...
  ... 0xffbd78b46618463550c18848539142a5e5af7da09859b063f7c2993f9590b65b
  VaccineControl: 0x6ddaa080a61aa07e5ae96ca3b3b61730434253e9
Saving successful migration to network...
  ... 0x6b036876e371afa38d8cd3fe06983c47b4281e59c7152849744726eb62f8b1db
Saving artifacts...
<font color="#8AE234"><b>willfreire@willfreire</b></font>:<font color="#729FCF"><b>/var/www/bck-eth-dapp-vaccine-control</b></font>$ npm install
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> bck-vaccine-control@1.0.0 No repository field.

audited 5729 packages in 10.327s
found <font color="#8AE234">0</font> vulnerabilities

<font color="#8AE234"><b>willfreire@willfreire</b></font>:<font color="#729FCF"><b>/var/www/bck-eth-dapp-vaccine-control</b></font>$ npm run dev

&gt; bck-vaccine-control@1.0.0 dev /var/www/bck-eth-dapp-vaccine-control
&gt; lite-server

** browser-sync config **
{ injectChanges: false,
  files: [ &apos;./**/*.{html,htm,css,js}&apos; ],
  watchOptions: { ignored: &apos;node_modules&apos; },
  server: 
   { baseDir: [ &apos;./src&apos;, &apos;./build/contracts&apos; ],
     middleware: [ [Function], [Function] ] } }
[<font color="#3465A4">Browsersync</font>] <b>Access URLs:</b>
<font color="#555753"> -----------------------------------</font>
       Local: <font color="#75507B">http://localhost:3000</font>
    External: <font color="#75507B">http://10.6.40.68:3000</font>
<font color="#555753"> -----------------------------------</font>
          UI: <font color="#75507B">http://localhost:3001</font>
 UI External: <font color="#75507B">http://localhost:3001</font>
<font color="#555753"> -----------------------------------</font>
[<font color="#3465A4">Browsersync</font>] Serving files from: <font color="#75507B">./src</font>
[<font color="#3465A4">Browsersync</font>] Serving files from: <font color="#75507B">./build/contracts</font>
[<font color="#3465A4">Browsersync</font>] Watching files...
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/index.html</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/css/bootstrap.min.css</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/js/app.js</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/js/bootstrap.min.js</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/js/web3.min.js</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/js/truffle-contract.js</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#C4A000">404</font> <font color="#75507B">GET</font> <font color="#555753">/favicon.ico</font>
<font color="#555753">18.11.01 14:07:15</font> <font color="#4E9A06">200</font> <font color="#75507B">GET</font> <font color="#555753">/VaccineControl.json</font>
</pre>

Correto?

Como eu simulo transações na **Rede Privada** pra mostrar no **MetaMask**, é possível fazer com este case?

**Comment by michelpf** [comment]
Ótimo.
No Metamask, você precisa selecionar a rede das já existentes, por isso que no Webminar pedi para configurarem o Ganache para a porta 8545 pois é padrão no Metamask. Se prefirir, clique em "Custom RPC" e coloque outra porta e/ou endereço.

![image](https://user-images.githubusercontent.com/8541053/47876334-cb2a2e80-ddf7-11e8-841e-03a9e614e26e.png)

**Comment by michelpf** [comment]
Acredito que tenha conseguido realizar seus testes. 👍
